# Email Address to use to send mails
sender_email = "csp@example.com"

# Email address to which the report mails are being sent
receiver_email = "alice@example.com"

# SMTP server address in following format: smtp.example.tld:465
smtp_address = "mail.example.com:587"

# SMTP username
smtp_username = "me@example.com"

# SMTP Password
smtp_password = "P4ssw0rd"

# Limit the requests a single IP address can make in an hour
rate_limit = 1

# address to bind to
bind_to = "localhost:8080"